<a href="https://colab.research.google.com/github/Leeminjun21/ABCD-A/blob/main/0411_ABDC_A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 😊1. 이것은 텍스트 셀입니다. 더블클릭하여 수정할 수 있습니다. 텍스트 파일은 마크다운 구문을 사용합니다. 수식을 작성할 때는 문장의 맨 앞과 뒤에 $ 표시를 하여 표시할 수 있습니다. 😊


$\sqrt{2x}+(1+x)^2$

# 2. 😊ls 를 사용하여 현재 디렉토리에 있는 파일 및 디렉토리 목록을 보여줍니다.😊

In [9]:
!ls /content

sample_data


# 3. 다음 셀을 실행하여 Python 작업을 실행할 수 있습니다. 실행을 중지하려면 런타임 -> 실행 중단 (단축키: Cmd/Ctrl-M I)를 선택하세요.

In [11]:
import time
print("Sleeping")
time.sleep(30) # sleep for a while; interrupt me!
print("Done Sleeping")

Sleeping


KeyboardInterrupt: 

# 4. 😊파일에 사용할 수 있는 모드 종류😊

In [18]:
f = open("numbers.txt", "w")
f.write("10\n20\n30\n40\n50")

#파일의 내용을 출력합니다.
with open("numbers.txt", "r") as f:
  for line in f:
    print(line.strip())

  f.close

10
20
30
40
50


# 5. 😊라이브러리 사용하기😊  dict를 사용하여 목록 작성

In [13]:
import pandas as pd

data = {
    '이름' : ['철수', '영희', '길동'],
    '나이' : [20, 21, 22],
    '성별' : ['남', '여', '남'],

}

df = pd. DataFrame(data)
print(df)

   이름  나이 성별
0  철수  20  남
1  영희  21  여
2  길동  22  남


# 6. 😊dict 사용한 예제😊

In [16]:
thisdict = {
    "brand" : "Ford",
    "model" : "Mustang" ,
    "year" : "1964" ,
}
thisdict.update({"coler": "red"})

print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': '1964', 'coler': 'red'}


# 7. 😊자신의 파이썬 버전 확인하는 명렁어
## 대부분 3.8.6 이상이다😊

In [ ]:
python -- verison

# 8. 😊numpy 라이브러리 사용하기😊

In [22]:
import numpy as np

# 1. 배열 생성
arr = np.array([1, 2, 3, 4, 5])

# 2. 배열 크기 확인
print(arr.shape)

# 3. 배열 자료형 확인
print(arr.dtype)

# 4. 배열 차원 확인
print(arr.ndim)

# 5. 배열의 모든 원소에 10을 더하기
arr += arr
print(arr)

# 6. 배열의 모든 원소를 2로 나누기
arr = arr.astype(np.float64)  #나머지가 부동 소숫점일 수 있어서 이렇게 해준다. 또는 int64로
arr /= 2
print(arr)

# 7. 배열의 평균 구하기
print(np.mean(arr))

# 8. 배열의 표준편차 구하기
print(np.std(arr))

# 9. 배열의 최댓값 구하기
print(np.max(arr))

# 10. 배열의 최솟값 구하기
print(np.sin(arr))


(5,)
int64
1
[ 2  4  6  8 10]
[1. 2. 3. 4. 5.]
3.0
1.4142135623730951
5.0
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [23]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


# 9. 😊pip는 파이썬에서 패키지 관리자이다😊

In [ ]:
C:\users\Your Name>pip install numpy